POST http://localhost:8080/customer
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"name": "Tracer", "email": "alreadytaken@gmail.com"}

###

POST http://localhost:8080/equipment
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "size": 160,
  "type": "snowboard",
  "available": true
}

###

POST http://localhost:8080/equipment
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "size": 190,
  "type": "snowboard",
  "available": true
}

###

POST http://localhost:8080/equipment
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "size": 561,
  "type": "delete_me XD",
  "available": true
}

###

POST http://localhost:8080/myOrder
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "dateFrom": "2019-01-01",
  "dateTo": "2020-01-01",
  "customerId": 21,
  "equipmentIds": [22]
}

###

GET http://localhost:8080/customer/all

###

PUT http://localhost:8080/equipment/2
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "size": 188,
  "type": "ski",
  "available": false
}
###

GET http://localhost:8080/equipment
###

GET http://localhost:8080/equipment/2
###

GET http://localhost:8080/equipment?type=ski&size=180
###

GET http://localhost:8080/equipment?available=true
###

GET http://localhost:8080/customer
###

GET http://localhost:8080/customer/1
###

GET http://localhost:8080/customer?name=Lee
###

GET http://localhost:8080/customer?email=nerf
###

GET http://localhost:8080/myOrder
###

GET http://localhost:8080/myOrder/16
###

GET http://localhost:8080/myOrder?customerName=Bastion
###

GET http://localhost:8080/myOrder?customerId=1
###

GET http://localhost:8080/welcome?text=our web
###

DELETE http://localhost:8080/equipment/5

###

DELETE http://localhost:8080/customer/7

###

DELETE http://localhost:8080/myOrder/23

###

DELETE http://localhost:8080/equipment/2

###

